---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb-pipeline
  namespace: core
spec:
  interval: 1m0s
  timeout: 5m
  path: ./control-plane/mongodb-pipeline/
  prune: true
  targetNamespace: core
  sourceRef:
    kind: GitRepository
    name: platform
    namespace: flux-system
