---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  #- cronjobs/backup-mongo-pipelinecore-no-audit-admin.yaml
  #- configmap/global-persistence-values.yaml
