---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-pipeline
  namespace: core
spec:
  interval: 5m
  chart:
    spec:
      chart: mongodb
      version: 14.4.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
#  valuesFrom:
#    - kind: ConfigMap
#      name: global-persistence-values
  values:
    replicaCount: 3
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    persistence:
      enabled: true
    image:
      registry: docker.io
      repository: bitnami/mongodb
      tag: 4.4.15
      pullPolicy: Always
      debug: true
    namespaceOverride: core
    fullnameOverride: mongodb-pipeline
    architecture: replicaset
    arbiter:
      enabled: false
    auth:
      enabled: true
      rootUser: root
